### ISSUE TITLE
ForTpetra: Index base argument to Map could cause headaches

### ISSUE THREAD

**Issue by tjfulle** [trilinos/ForTrilinos#103]
@aprokop and I just discussed the following issue offline and thought it good to document it here.  Perhaps @mhoemmen also has an opinion?

`Tpetra::Map` objects take `indexBase` as an argument.  `indexBase` is required to be the minimum global id (GID) and defaults to 0 in C++ codes.  In ForTpetra, it is typical to use `indexBase` equal to 1, since Fortran array indexing starts at 1 - but that is only the default behavior.  Fortran arrays can be defined over an arbitrary range:

```fortran
real(kind=the_kind) :: a(10), b(-5:5)
```
both `a` and `b` have the same dimension, but different index ranges.  I'm not sure how the array `b` would look compared to `a` when passed to C++.

I believe ForTpetra has hardcoded some conversions to go back and forth between 0 C based indexing and 1 Fortran based indexing.  But, if a user defined the Fortran array with arbitrary range, the hard coded conversions could be incorrect.

I suggest removing the `indexBase` option from ForTpetra all together and requiring it always be the Fortran default of 1.  1 could then be hard-coded in the C++ wrappers and sent to Tpetra.  Further, it should be documented that ForTrilinos assumes that *all* Fortran arrays are indexed from 1.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> indexBase is required to be the minimum global id (GID)

This was a historical issue which I may have since fixed.  The "index base" is really just a C vs. Fortran thing, and it only applies / should apply to the creation of contiguous Maps.  If users just supply an index range, it's up to them to decide the minimum GID.
