### ISSUE TITLE
ierr and serr module of origin

### ISSUE THREAD

**Issue by tjfulle** [trilinos/ForTrilinos#119]
`ierr` and `serr` are defined in the `forteuchos` module.  It would be convenient if, instead, they lived in their own module, independent of `forteuchos`.  Perhaps `forerrcnt`?  See [this comment](https://github.com/trilinos/ForTrilinos/pull/118#issuecomment-347922909) for a use case where this would be helpful. 

@aprokop @sethrj

**Comment by sethrj** [comment]
Sure, I just put them in `forteuchos` because (to my knowledge) everything in trilinos is downstream of it. The instantiations of `std_x` etc. might also be good to have in there as well.

**Comment by aprokop** [comment]
The thing I don't like here is having an extra module to be included every time one of ForTrilinos modules is included. Is there a method to avoid that?

**Comment by aprokop** [comment]
This is going to be fixed by #169.

**Comment by tjfulle** [comment]
@aprokop said:

> The thing I don't like here is having an extra module to be included every time one of ForTrilinos modules is included. Is there a method to avoid that?

That is already a requirement, right?  For any package other than teuchos, you have to `use forteuchos` to get access to `ierr` and `serr`.  I think `#include “ForTrilinos.h”` is the cleanest, and most intuitive, option.  The header can include any mandatory `use` statements.

**Comment by aprokop** [comment]
@tjfulle I agree with you and that's why I followed your advice in the PR. I'm OK to always include `ForTrilinos.h`.

**Comment by aprokop** [comment]
For the most part, done in #169.
