### ISSUE TITLE
TpetraMultiVector test coverage

### ISSUE THREAD

**Issue by tjfulle** [trilinos/ForTrilinos#121]

**Comment by tjfulle** [comment]
PR #122 goes a long way to getting pretty complete test coverage for `TpetraMultiVector`.  There are many "skeleton" tests in `test_tpetra_multivector.f90` that are commented out that can be activated by uncommenting the skeleton and completing the implementation.

**Comment by aprokop** [comment]
We can start uncommenting tests.

**Comment by aprokop** [comment]
Fixed by #262.
