### ISSUE TITLE
Should we prefix ForTrilinos classes

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#128]
Right now, if
```fortran
use fortpetra
```
one gets `TpetraCrsMatrix`, etc. 

1. Is this a good approach?
2. Should we prefix the names with something common to the full ForTrilinos repo? Like `FTTpetraCrsMatrix`?
3. Should we remove mention of specific package from class names and use generic `ForTrilinosCrsMatrix`?

**Comment by aprokop** [comment]
@kevans32 @mattbement @sethrj @bscollin @tjfulle

**Comment by tjfulle** [comment]
Sorry @aprokop , I thought I had replied sooner.

If the intended outcome is for users to see the ForTrilinos product as an end in and of itself, with Trilinos merely being a black box backend, I’d vote for not prefixing objects with different packages in favor of `ForTrilinosMultiVector`, `ForTrilinosCrsMatrix`, etc.  But, if ForTrilinos is to be a transparent layer between Trilinos and Fortran, I’d leave it as is.

**Comment by kevans32** [comment]
Yea I think we should retain the specific package info and have something common to the full FT repo, so leave as is.

**Comment by aprokop** [comment]
OK, no it is. Leaving as `TpetraCrsMatrix` and such.
