### ISSUE TITLE
Tpetra{Export,Import} test coverage 

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#136]

**Comment by tjfulle** [comment]
@aprokop , I have the tests done.  But, to properly test `import` and `export`, the `doImport` and `doExport` methods of `TpetraMultivector`, `TpetraCrsGraph`, and `TpetraCrsMatrix` need to be implemented.  `TpetraMultiVector` is the priority to push the current tests.

**Comment by aprokop** [comment]
Great.

Yes, I've dragging my feet on implementing those. Can't do them automatically (as they belong to the base class), but can do semi-automatically and that should not be hard. Are `doImport` and `doExport` of the classes you listed the only things you need?

**Comment by tjfulle** [comment]
As of right now, yes.  The tests I have written are invalid until there is actually something imported/exported to check :)

**Comment by tjfulle** [comment]
The tests only use `TpetraMultiVector`

**Comment by aprokop** [comment]
I have a patch that does `doImport` and `doExport`, but unfortunately, it does not compile right now due to the clash in `zero`: some tests define zero, and another zero is coming from Tpetra's CombineMode.

**Comment by aprokop** [comment]
Now that #178 is merged, I hope that's sufficient for you to finish the tests.

**Comment by aprokop** [comment]
Fixed in #180.

**Comment by aprokop** [comment]
Actually, lets keep it open until we get 100% coverage of the classes.

**Comment by aprokop** [comment]
Fixed by #262.

**Comment by aprokop** [comment]
Fixed by #262.
