### ISSUE TITLE
Switch branches for release

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#151]
Steps:
- [x] Merge current `develop` into `master`
    The older releases would still be available in history and the corresponding release branches/tags.
- [x] Update `README.md`
- [ ] Merge current develop into `12.12` branch
    This is retroactive, but apparently for some reason it already contains the new ForTrilnos code. Thus it makes total sense. But need to get approval from @bmpersc.
- [ ] Update Trilinos' spack package to make sure `fortrilinos` variant requires trilinos 12.12.1

I don't know if we should follow a 2-branch develop model, or just use `master`. In any case, the `master` would *not* follow Trilinos' `master` as that may be too much work. Maybe we need to evaluate that.

**Comment by tjfulle** [comment]
What about a snapshot approach similar to Kokkos, SEACAS, etc?

**Comment by aprokop** [comment]
We'll need to set up a meeting with @bmpersc and @jwillenbring to figure the process out.

Forgot about the patches. I think they could be backported to Trilinos 12-12-1 branch, though.

**Comment by tjfulle** [comment]
The biggest complaint I hear from non Trilinos developers about Trilinos is how hard it is to build.  I’m sure any reduction in steps needed to build ForTrilinos would be welcome by most.

**Comment by kevans32** [comment]
Preach


________________________________

**Comment by aprokop** [comment]
Apparently, the process may not be as easy as I thought. See #195 .
