### ISSUE TITLE
Hit 132 character limit

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#153]
- [x] Teuchos
  - [x] Source
  - [x] Tests
- [x] Tpetra
  - [x] Source
  - [x] Tests
  - [x] Tutorial
    Do not use `EXPECT_TRUE` and other testing macros in tutorial, replace them by something a Fortran user will recognize.
- [ ] Simple
  - [x] Source
  - [ ] Tests
- [x] Belos
  - [x] Source
  - [x] Tests

**Comment by tjfulle** [comment]
Tpetra tutorials are now from of `FortranTestMacros.h` (#168)

**Comment by aprokop** [comment]
OK, the only thing remaining here is to update `simple` tests (similarly to tutorial) to fit into 132 char limit, and we will be able to compile with `flang`.

**Comment by tjfulle** [comment]
I’m early done with ImportExport tests (they enemies up being more complicated than I originally thought).  When that is done, I can get the simple stuff done pretty quickly.  That will be the last remaining code using FortranTestMacros.h
