### ISSUE TITLE
.neqv. broken in GCC 7.?

### ISSUE THREAD

**Issue by tjfulle** [trilinos/ForTrilinos#170]
@aprokop reported that

```
if (a .neqv. b) then
 ...
end if
```

gives erroneous results.  The culprit seems to be `.neqv.`.  I have not been able to reproduce the failures with GCC 6.4.

**Comment by aprokop** [comment]
More background for the issue.

The comparison `a. eqv. b` and `a. neqv. b` fail when `a = c_associated(x)` and `b = true` even though both `a` and `b` are individually true. There is clearly something wrong as
```fortran
WRITE(*,"(L1,L2,L2,L2)") a, b, a.eqv.b, a.neqv.b
```
produces `T T F T` which does not make any sense.

Online search seems to pick up a compiler bug [issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83254). It seems to affect gfortran 7.1 and 7.2. It is fixed upstream but has not been backported yet.

**Comment by tjfulle** [comment]
Workaround provided in #171
