### ISSUE TITLE
Fix compilation issues for --std=f2003

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#183]
Currently, when specifying `--std=f2003` to Fortran compilation flags, the build fails. For instance, 
```
/home/xap/code/trilinos/fortrilinos/packages/ForTrilinos/src/utils/src/fortest.f90:139:17:                                                                    
                                       
     stop stopcode                                                                                                                                            
                 1                     
Error: STOP code at (1) contains too many digits   
```
This needs fixing. I think this may be one of the features introduces in 2008, as it compiles fine with `--std=f2008`.

**Comment by aprokop** [comment]
According to [this](https://stackoverflow.com/questions/17446557/stop-code-in-variable):
```
Up to Fortran 2003 the stop code can be either a scalar-char-constant or a sequence of up to 5 
digits. A scalar-char-constant means what others might call a string, eg your "err" but not your 
err_msg.

In Fortran 2008 the stop code can be an expression which returns either a scalar-default-char-
constant-expr or a scalar-int-constant-expr. If you had a Fortran 2008 compliant compiler then you 
could use a parameter (eg something declared as character(len=3), parameter :: err_msg = "err") as 
a stop code
```
In DBCF we use `stop DBC_ASSERT_FAIL` with `#define DBC_ASSERT_FAIL 993399`, a **six**-digit number which is disallowed by Fortran 2003.

**Comment by tjfulle** [comment]
I also copied the value from DBCF in to FortranTestUtilities.  Maybe it’s better to just use ierr?

**Comment by aprokop** [comment]
@tjfulle I have a patch in progress that removes DBCF and fixes the stop in `FortranTestUtilties` by truncating it by 1 character. This makes things pass.

**Comment by tjfulle** [comment]
Wasn’t the value chosen to signal a specific error?  I recall reading that in the bdcf file

**Comment by aprokop** [comment]
> Wasn’t the value chosen to signal a specific error? I recall reading that in the bdcf file

Can't find any comment indicating that.

**Comment by tjfulle** [comment]
I probably just (dangerously) inferred that from the fact there were two error codes defined in the dbcf header

**Comment by tjfulle** [comment]
Did the DBCF version also fail to compile?  I only ask because it uses a literal constant and FortrilinosTesUtilities used a integer parameter.  I was just wondering if there was a difference

**Comment by aprokop** [comment]
> Did the DBCF version also fail to compile?

Yes.
