### ISSUE TITLE
Provide an API to return ForTrilinos version

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#186]
Required policy for xSDK, see #172.

**Comment by sethrj** [comment]
I have a CMake+Python+C++ script that I use in our Exnihilo code to propagate configuration and version information. It should be pretty easy to pull into ForTrilinos if you'd like me to -- I don't know if the Trilinos build system already has something similar though that you'd prefer.

**Comment by sethrj** [comment]
This is implemented.
