### ISSUE TITLE
Fix build badges issue

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#190]
Right now, both build badges from both `master` and `develop`branches point to the same build. We need to separate them somehow. @dalg24 Do I need to create a new Jenkins build configuration for my master branch even if I want master and develop to do essentially the same CI testing? Or is there a way to avoid that?

**Comment by dalg24** [comment]
Duh :)

**Comment by aprokop** [comment]
I think the solution right now is to duplicate the continuous build and rename it to something else. But first, fix #187.

**Comment by aprokop** [comment]
Fixed the badges. The problem now is that `README.md` in `master` and `develop` have conflicts. How are we going to merge `develop` to `master` next time? Is there a way to merge ignoring specific files?

**Comment by aprokop** [comment]
For now, it's all manual. Reopen when I get sick and tired of that.
