### ISSUE TITLE
Support int/long global types

### ISSUE THREAD

**Issue by sethrj** [trilinos/ForTrilinos#286]
Spack and E4S by default use `long` global int types. We should be able to support this by regenerating (on-the-fly) the bindings with swig-fortran. Or we should use `long` by default and `long long` only with SWIG-fortran, since on 64-bit Unix systems `sizeof(long) == sizeof(long long)`. @aprokop any thoughts on the default global type?

**Comment by aprokop** [comment]
Not following.

> Spack and E4S by default use `long` global int types.

What does this mean? Don't they simply provide a way to install packages, and it's up to the package to decide? It would have made a bit more sense if you were talking about xSDK.

> We should be able to support this by regenerating (on-the-fly) the bindings with swig-fortran.

When would this on-the-fly happen? When calling `spack install` command?

> Or we should use long by default and long long only with SWIG-fortran, since on 64-bit Unix systems sizeof(long) == sizeof(long long).

What does make sense on the Fortran side?

> @aprokop any thoughts on the default global type?

I'd check the current recommendation by the Trilinos team, as I don't even know if they properly test both.

**Comment by sethrj** [comment]
- Spack's default variant is `gotype=long`, and the [E4S spack environment](https://github.com/E4S-Project/e4s/blob/master/environments/21.08/spack.yaml) (which is basically what E4S is) explicitly specifies `gotype=long`.
- on-the-fly was a poor choice of words: I meant at configure/build time updating the necessary code for using a different int type.
- I would guess that `gotype=int` might be more sensible on the fortran side to be fortran-y, but for large problem sizes that obviously won't do. Probably best to find the target applications e.g. E3SM.
- Good point. I have no idea what tribits variable combinations are used, or what tpetra template types are tested, or even why `long` is the default. The `xsdk` recipe uses `int` which seems bizarre: seems like exascale would be likely to have more than 2B global unknowns. dealii requires `gotype=int`. Maybe I should just change the default type in the trilinos spack recipe but I'm not sure of the consequences....

**Comment by sethrj** [comment]
So maybe the best approach is to leave it `long long` (since that seems to be the preferred type in the trilinos cmake logic) and support other types so that fortrilinos can be used with xsdk/e4s without a duplicate installation of trilinos.

**Comment by aprokop** [comment]
In your E4S link, I see the trilinos receipt specifying Trilinos' `gotype` to `long_long`.

So, to summarize:
xsdk -> `trilinos gotype=int`
e4s  -> `trilinos gotype=long_long`
fortrilinos -> `gotype=long_long` (currently)

Overall, I think that we should align ForTrilinos with E4S, whatever that is. I see xsdk as lower priority. If we do want go be included in xsdk, we can follow your suggestion of generating it on the fly.

As an alternative, we could carry multiple pre-generated versions for different `gotype`. Then choose one of them during the configuration.

**Comment by sethrj** [comment]
Oh odd, I didn't see that it is long long now...

**Comment by sethrj** [comment]
see https://github.com/spack/spack/pull/26253 .

**Comment by aprokop** [comment]
The default for global ordinal in Trilinos is still `long`. Just E4S sets it to `long_long`.
