### ISSUE TITLE
Remove old stale branches

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#29]
@bmpersc @jwillenbring @trilinos/framework 

In the ForTrilinos repo we have old branches that may have been migrated during the move to github but have nothing to do with the ForTrilinos repo:
- tribits_github_snapshot
- panzer_stk_conversion

Can we remove those?

**Comment by youngmit** [comment]
No complaints from me

**Comment by aprokop** [comment]
Removed the branches. Just because.
