### ISSUE TITLE
Mikado

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#31]
Nico Schlomer has a [Mikado](https://github.com/nschloe/mikado) repo that provides a simple interface to Trilinos. I wonder if we can leverage some of that for simple drivers in ForTrilinos.

**Comment by sethrj** [comment]
Looks like it uses `boost::any` in lieu of `ParameterList`, which I think would make wrapping harder. Plus, I'm not seeing any MPI support in there, and the code base looks rather small...

**Comment by aprokop** [comment]
We will not use it, but I was hoping to lift their nonlinear code. I'm less familiar with a world of NOX/LOCA/Thyra and feel like this would be a good start to add nonlinear operators to a simple driver.

**Comment by aprokop** [comment]
We are moving in a different direction.
