### ISSUE TITLE
Add simple interface for Eigen solvers

### ISSUE THREAD

**Issue by youngmit** [trilinos/ForTrilinos#35]
This will be a little more difficult than the linear solvers that are currently in the TrilinosHandle class, since there is no abstraction layer like Stratimikos sitting on top of Anasazi. For a user to be able to select the type of SolverManager to use, we will need some scaffolding to handle that.

I guess another question would be how this will interact with the existing TrilinosHandle code. Should we modify TrilinosHandle to have Eigen solver capability, or should we make a separate class to handle Eigensolvers?

**Comment by aprokop** [comment]
Implementing it is not hard. I'm not sure at this point, but it may be better to start with an independent class for it. 

The tricky part is designing the interface. The main thing: what should we use instead of
```c++
    void solve(int size, const double* rhs, double* lhs) const;
```
Should we do
```c++
    void solve(int num_eigenvalues, double * eigenvalues, int size, double * eigenvectors) const;
```
I guess `eigenvectors` would correspond to a multi-dimensional Fortran array?

**Comment by aprokop** [comment]
Brief summary of the chat:
- `c_f_pointer` may work but need to do the matching
- @youngmit will take a look at SWIG transformation
- @aprokop will start with a simple one eigenvector case

**Comment by aprokop** [comment]
The first version has been pushed.

**Comment by aprokop** [comment]
The new version has been pushed. The new interface uses wrapped `Tpetra::MultiVector`, and thus properly supports multiple eigenvectors.
