### ISSUE TITLE
F17Q4 milestone: Complete tools and processes assessment to leverage Trilinos from Fortran

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#37]
**Description**
Based on the needs of the target Fortran codes, determine the tools and processes necessary to create the capabilities within Phase 1 ForTrilinos

**Plan**
- Decide on C++ intrinsics that are needed to support the Fortran interface (e.g. functions, classes, inheritance, templates)
- Determine which Trilinos packages and classes are needed for initial ForTrilinos to support MPACT and CAM
- Assess feasibility of using PyTrilinos SWIG wrappers for construction of ForTrilinos SWIG interface files

**Completion**
Prioritized list of functionalities to provide as part of Phase 1 and 2

**Comment by kevans32** [comment]
Discussion of these is on confluence page from 9/20. Mitch writing report and then we will close this out

**Comment by kevans32** [comment]
Report uploaded to ECP reporting on confluence. Closed JIRA issue.
