### ISSUE TITLE
F18Q1 milestone: complete phase 1 ForTrilinos release

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#38]
**Description**

**Plan**
- Extend SWIG to create Fortran wrappers for C++ code with production-level reliability
- Create initial SWIG interface files to Trilinos packages
- Create basic suite of functions and tools to access Trilinos with Fortran calls
- Implement and test within MPACT
- Release as part of github repo of ForTrilinos

**Criteria**
Phase 1 is successfully implemented within a test case of the MPACT code. New ForTrilinos code shipped with the main Trilinos code. Pull request of SWIG/Fortran submitted to mainline SWIG development.

**Comment by kevans32** [comment]
Release timeline and remaining tasks:
Monday Dec 18, 3pm EST Kate present dry run of talk to team
Tuesday Dec. 19, 10:15 AM Kate present review talk to ECP folks, team present
Thursday Dec 21, Submit F18Q1 Milestone report (Kate 1st draft, @aprokop  update)
Thursday Dec 21, Submit F18Q1 Milestone highlight slides (@aprokop  1st draft, Kate update)
Thursday Dec 21, click the JIRA button to officially close the milestone 
(quarterly report? Kate is inquiring)
Tasks and issues to tackle/think about before release:
Complete code capability needed in release (pretty much there)
Inheritance issue (its a long term risk, need to discuss)
Documentation (Doxy is an issue so use what is there in tests and examples, @tjfulle and @aprokop, create a short users guide to go with these)
Tests (several days of work left by @tjfulle)
Examples 
SWIG limitations using Kokkos are becoming apparent when using advanced C++
Performance (4x WCS calling element by element, but usually much less. with LTO, its better)
ID users and those who we could impact with capability
Set date for release party. @tjfulle  I assume little twins preclude travel to ECP in Feb?

In the new year:
Implement and test in MPACT, Ben will do with @mattbement helping 
Implement and test in Truchas, @mattbement

**Comment by aprokop** [comment]
Done.
