### ISSUE TITLE
Framework: enable CI testing

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#4]
This issues is to track status of Jenkins CI testing.
- [x] Create a Docker container with Trilinos TPL similar to how DTK does it
- [x] Make sure tests pass in the container
- [x] Hook up Jenkins CI with Github
- [x] Configure Jenkins to launch CI on PR

**Comment by aprokop** [comment]
Fixed in #5.

**Comment by jwillenbring** [comment]
@aprokop How much would would it be to generalize what you did here to work for all of Trilinos?

**Comment by aprokop** [comment]
@jwillenbring Not much. Essentially, just need to update the Dockerfile script to provide all TPLs required for testing, and create Jenkins configuration to run things. Though, I was not the person who set up the Jenkins installation from scratch, I just used the existing infrastructure of the [DTK](https://github.com/ORNL-CEES/DataTransferKit). But I know the person who set it up.

If you are interested, I can provide more info on how things work.

**Comment by jwillenbring** [comment]
@aprokop I would be interested. How much time would you estimate you spent on this?

**Comment by aprokop** [comment]
Around couple hours to set up the Docker, and a day for Jenkins (I think I got hit by some bug in Jenkins where copying an existing configuration is *not* the same as creating one from scratch, even though at the end they would have the exact same configuration).

**Comment by aprokop** [comment]
Just testing Slack integration.

**Comment by aprokop** [comment]
My colleague has accidentally deleted the Jenkins configuration for CI. I need to resurrect it now.

**Comment by aprokop** [comment]
OK, redid the hooks and Jenkins configuration. Works on PR now.

**Comment by aprokop** [comment]
We currently have only testing for PRs, but we do not test `develop` branch after merging. This should be done.

**Comment by aprokop** [comment]
My first at CI on `develop` does not work. I have a Jenkins configuration, and a webhook installed, but the webhook is not triggered on the Github side with a merged PR.

**Comment by aprokop** [comment]
Alright, I did not change anything, but my colleague did some changes to the Jenkins config, and now things seem to work. I see Github payload delivered to Jenkins, and build triggered. Will test on one more PR merge, and if things go right we should get a proper CI badge in README on `develop`.

**Comment by aprokop** [comment]
Still, no clue about why Jenkins badge does not display properly. Talking to Damien did not help. Googling did not help either.

Thing searched:
- Aggressive Github caching
- Reverse proxies
- shields.io workaround
- ...
