### ISSUE TITLE
Framework: Regenerate wrapper files for changed typemaps

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#48]
At the moment, the wrapper files in ForTrilinos source are regenerated only if `.i` file have changed. However, this breaks down if we simultaneously develop SWIG which updates the `.swg` typemaps and such. In my case, my ForTrilinos is configured to depend on swig in `~/local/opt/swig`. I install it there manually through running `make install` in the swig directory. However, newly installed files are not picked up automatically thus wrapper files are not regenerated.

One workaround I can think of is to configure CMake to point to the *sources* of SWIG somehow.

@sethrj Can you share your workflow? I noticed that you did not run `make install` yourself.

**Comment by sethrj** [comment]
@aprokop I have symlinked `${SWIG_INSTALL}/share/swig/4.0.0` to `${SWIG_SOURCE}/Lib`, and use the following when configuring Trilinos:
```
  -D SWIG_EXECUTABLE:PATH="${SWIG_BUILD}/swig" \
  -D SWIG_DIR:PATH="${SWIG_INSTALL}/share/4.0.0" \
```

**Comment by aprokop** [comment]
I'll add RTD documentation for this. Why do you then need a `SWIG_INSTALL`? And what is your `SWIG_BUILD`?

**Comment by sethrj** [comment]
I probably don't need SWIG to be actually installed for ForTrilinos, but I was doing other testing that required it. SWIG_BUILD is just the build directory (I do out-of-tree builds).

**Comment by aprokop** [comment]
I think it still does not fix the issue. I've tried this approach but it essentially only allows skipping `make install` step, but does not regenerate the files if any of the `.swg` in `swig/Lib/fortran/` changed.

**Comment by aprokop** [comment]
Closing as we regularly regenerate the typemaps.
