### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#6]
1. What is ForTrilinos license?
2. Are all files licensed the same?
3. Should ForTrilinos version 2 have the same license?

**Comment by aprokop** [comment]
Ping @maherou and @bmpersc.

**Comment by maherou** [comment]
ForTrilinos should already have, and continue to have, [the 3-clause "new" BSD license] (https://opensource.org/licenses/BSD-3-Clause).  It should be used for all files.  If there are discrepancies in the present files, the text should be changed to the 3-clause text.  A spot check of files seems to indicate that the license language is correct in at least some of them.
