### ISSUE TITLE
Using long macros seem to exceed 132 character line length

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#63]
@sethrj  @youngmit @bscollin

I did a quick attempt at using [flang](github.com/flang-compiler/flang) with ForTrilinos. It compiles the source just fine, but is getting stuck in tests with the following errors all over the place:

`F90-S-0285-Source line too long`

It seems that Fortran 2003 standard limits the number of characters in a line to 132 in the free form (and to 72 in fixed). It would be fine with continuation lines, but I think the macros in the test (like `EXPECT_EQ`) are assembled in a single line that exceeds the length. 

My question is: is using long macros standard-compliant? Or is it just a feature that ifort/gfortran support?

**Comment by bscollin** [comment]
So yeah... we have the same issue.  gfortran has a way to make the line length arbitrary but ifort does not.

**Comment by aprokop** [comment]
So what is the workaround? Simply not use long macros?

**Comment by youngmit** [comment]
unfortunately, yes. Or use another mechanism that can support multi-line expansions

**Comment by aprokop** [comment]
With recent changes to the testing I was able to compile ForTrilinos with flang (at least in serial). Closing for now.
