### ISSUE TITLE
Create a shortcut approach to using Trilinos

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#8]
While the eventual goal is to expose a significant portion of Trilinos functionality to Fortran applications, it is a good idea to expose the potential applications to the benefits of Trilinos as early as possible.

The idea is to provide a minimal interface (not existing in Trilinos proper at this point) which would solve a linear systems given few Fortran arrays with data corresponding to matrix and vector, a communicator, and a parameter list. Something like this (on C++ side):
```c++
int solve_linear_system(
  MPI_Comm comm,
  const int * row_ptrs, int num_rows,
  const int * col_inds, int num_values 
  const double * vals, int num_values,
  const double * rhs, int size,
  double * sol, int size,
  const ParameterList* list);
```
Not all sizes are necessary, but it makes it easier to convert from Fortran.

On the C++ side we wrap the data in the proper Trilinos classes (and constructing missing ones like `Map`), and pass it to Stratimikos.

**Comment by sethrj** [comment]
Ross used static RCPs to allow this kind of thing to be broken into multiple function calls; maybe we'd want to do something similar to allow a little more flexibility?

**Comment by aprokop** [comment]
We certainly could, but that would also require storing temporary handles on the Fortran side between code. Having it in one function would bypass that.

**Comment by sethrj** [comment]
not really, he only needed handles because he used multiple instances; for simple trilinos we'd only need a single instance; and all the function calls would be module-level functions

**Comment by sethrj** [comment]
I envision an interface like:
```
void init();
void init(MPI_COMM comm);
void build_crs(int size, int* i, int* j, double* v);
void set_params(RCP<ParameterList>& p);
void solve(int size, const double* b, double* x);
void finalize();
```
and on the backend have
```
RCP<Comm> comm;
RCP<Solver> solver;
```
and so forth that get built during `init` and reset in `finalize`

**Comment by aprokop** [comment]
Here is a modified version:
```C++
void init();
void init(MPI_COMM comm);
void setup_matrix(int num_rows, const int* i, int num_nnz, const int* j, const double* v);
void set_params(const RCP<ParameterList>& p);
void setup_solver();
void solve(int size, const double* b, double* x);
void finalize();
```
The main difference is adding a second size for nnz in the matrix construction, and separating the solver setup from the solve. This should allow a more clear idea about when a solver is constructed, and when a system is solved.

**Comment by sethrj** [comment]
Sure, that looks good. My code snippet was just as an example of what I meant by separate functions. You could also probably combine "set_params" into setup_solver.

**Comment by aprokop** [comment]
One thing that I'm slightly concerned about is that users may accidentally setup a system using one matrix, and then setup for a different matrix overriding the first one. Having a handle, or an id, would fix that. But it may be out of scope of this issue.

**Comment by sethrj** [comment]
I was operating under the assumption of one solver, one matrix, one parameter list to get started. It would be nice to know the distribution of "needed functionality" vs number of users (i.e. would a single matrix cover 10% of use cases?)

**Comment by aprokop** [comment]
I agree that we should target that use case. But we also want to prevent user mistakes, as eventually they would come to us if something does not work.

An easier fix would be to simply disallow calling `setup_matrix` and `setup_solver` for the second time until `finalize()` is called.

**Comment by sethrj** [comment]
Yep, that's what I was thinking. Leave the objects unallocated until the call, and assert at the beginning of the call that they haven't been allocated.

**Comment by aprokop** [comment]
Current interface is not sufficient. We missed on the parallel component. The 
```C++
 void setup_matrix(int num_rows, const int* i, int num_nnz, const int* j, const double* v);
```
has few issues:
1. We don't know which global rows the provided rows correspond to. `i` here is only about offset into `j`. 
2. It is not clear whether column indices in `j` are global (they probably are).

It could be fixed by 
a) requiring/making sure indices in `j` are global
b) taking in an extra `int* rows` array to denote the rows

A variation of interface could be to take in triplets (which may be easier or an alternative to the current one)
```
void setup_matrix(int num_rows, const int* rows, const int* row_offsets, int num_nnz, const int* cols, const double* vals)
```

Also, while implementing #14, it seems like we may need to copy data. The first reason is that Tpetra takes in `size_t` arrays for row offsets. (could potentially be fixed by tweaking `setup_matrix` interface). The second reason (I'm not 100% sure yet) is that it seems that Tpetra can only construct a matrix from 3 arrays if it is in the data it itself allocated.

I'm going to move forward right now with an extra array interface to get us started (i.e., implementing a) and b)).

**Comment by aprokop** [comment]
Some ideas of how to enable IoC for preconditioners: the easiest approach may be (based on MueLu)
- [ ] Register a "CUSTOM" name with `LinearSolverBuilder`
  Look at MueLu's `enableMueLuPreconditioner`
- [ ] Implement `FortranPreconditionerFactory`
  Look at MueLu's `MueLuPreconditionerFactory`
  I think we will simply ignore `const RCP<const LinearOpSourceBase<Scalar> >& fwdOpSrc` argument as a user will provide the operator.

**Comment by aprokop** [comment]
The first version is in. For now, inversion-of-control (Operator and custom preconditioners) are disabled.
