### ISSUE TITLE
Make template arguments CMake configurable

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#88]
Right now, `Scalar`, `LocalOrdinal`, `GlobalOrdinal` are hardcoded to `double`, `int`, `int`. We should allow an option to configure those (or, at the minimum, `GlobalOrdinal`) to be set to a different type (like `long`). This should only be allowed when in developer mode, as it will may modify the `.f90` files that we carry.

We should also decide on the data type for `GlobalOrdinal` that we carry. One could argue that we should carry 64-bit integers instead of 32-bit. I think Trilinos is leaning that way to reduce the number of instantiations. We could also carry two versions of classes and enable one of them depending on how Tpetra is configured.

**Comment by sethrj** [comment]
Might make sense to add TriBITS options for the variable types, then inject them into a `config.h` file, which then `%include` with SWIG. Agree it only makes sense to do in "developer" mode.

**Comment by aprokop** [comment]
This issue is blocked by the fact that right now there are a few places where we have to use defined value rather than alias. For instance, in `Map` and in `typemap(in)`. Until those are resolved, we cannot fix this.

**Comment by aprokop** [comment]
The defaults for `Scalar`, `LocalOrdinal`, `GlobalOrdinal` are hardcoded. The `node` is changeable by #265. This is sufficient.
