### ISSUE TITLE
Desired functionality by MFiX

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#89]
@kvmkrao

**Comment by kvmkrao** [comment]
> Intialize A
> Intialize b
> 
_> form the objects for A and b
> Use InsertGlobalValues and FillComplete to make A_
> 
> Start iteration loop
> 
> call to form A x1 = b for a fluid variable x1 
(An iterative solver in MFiX is employed to solve the linear system)
> update the fluid variable x1 field
> 
> call to form A x2 = b for another variable x2
(A  solver in Trilinos is employed to solve the linear system)
>    pass A and b arrays to the ForTrilinos/C++ wrapper to modify the Values of the objects
>    _Use ReplaceGlobalValues to modify the object for A_
>    form the linear system 
>    solve the linear system for x2
> 
> update the fluid variable x2 field
> End iteration loop

**Comment by tjfulle** [comment]
@kvmkrao, @aprokop if by "`A`" you mean a `TpetraCrsMatrix`, this functionality exists.  See the [Power Method Tutorial](https://github.com/trilinos/ForTrilinos/blob/develop/src/tpetra/tutorials/PowerMethod.f90) for an example.

**Comment by aprokop** [comment]
This has been implemented and tested.
